size_thresholds:
  max_members_group: 10000
  max_members_channel: 50000

owned_groups:
  enabled: true
  backdays: 7
  limit: 10
  whitelist: []
  blacklist: []
  download_attachments: false
  skip_big: true

owned_channels:
  enabled: true
  backdays: 7
  limit: 10
  whitelist: []
  blacklist: []
  download_attachments: false
  skip_big: true

other_groups:
  enabled: true
  backdays: 7
  limit: 10
  whitelist: []
  blacklist: []
  download_attachments: false
  skip_big: true

other_channels:
  enabled: true
  backdays: 7
  limit: 10
  whitelist: []
  blacklist: []
  download_attachments: false
  skip_big: true

private_chats:
  enabled: true
  backdays: 7
  limit: 10
  whitelist: []
  blacklist: []
  download_attachments: false
  skip_big: false

bots:
  enabled: true
  backdays: 7
  limit: 10
  whitelist: ["test_bot"]
  blacklist: []
  download_attachments: false
  skip_big: false 